- hosts: bind
  become: true
  roles:
    - { role: bind-server , tags: 'bind-server'}

- hosts: freeipa_server
  become: true
  roles:
    - { role: freeipa-server , tags: 'freeipa-server'}

- hosts: freeipa_client
  become: true
  roles:
    - { role: freeipa-client , tags: 'freeipa-client'}

- hosts: freeipa_group
  become: true
  roles:
    - { role: freeipa-group , tags: 'freeipa-group'}

- hosts: freeipa_user
  become: true
  roles:
    - { role: freeipa-user , tags: 'freeipa-user' }

- hosts: ntp_server
  become: true
  roles:
    - { role: ntp-server , tags: 'ntp-server'}

- hosts: ntp_client
  become: true
  roles:
    - { role: ntp-client , tags: 'ntp-client'}

- hosts: rsyslog_server
  become: true
  roles:
    - { role: rsyslog-server , tags: 'rsyslog-server'}

- hosts: rsyslog_client
  become: true
  roles:
    - { role: rsyslog-client , tags: 'rsyslog-client'}