- name: ntp server installation
  dnf:
    name: chrony
    state: present
- name: enable and start ntp service
  systemd:
    name: chronyd
    state: started
    enabled: yes
- name: backup chrony.conf configuration
  copy:
    src: /etc/chrony.conf
    dest: /etc/chrony.conf.{{ansible_date_time.date}}.backup
    remote_src: true
- name: add timeserver config in chrony.conf
  lineinfile:
    path: /etc/chrony.conf
    regexp: '^pool|^server'
    line: "{{ ntp_server.time_server_config }}"
    # backup: true
- name: add client network in chrony.conf
  lineinfile:
    path: /etc/chrony.conf
    regexp: '^\#allow'
    line: "{{ ntp_server.client_network }}"
- name: restart ntp service
  systemd:
    name: chronyd
    state: restarted