
- name: bind installation
  dnf:
    name: '{{ item }}'
    state: present
  with_items: '{{ bind.bind_packages }}'
- name: enable and start named service
  systemd:
    name: named
    state: started
    enabled: yes
- name: backup named configuration
  copy:
    src: /etc/named.conf
    dest: /etc/named.conf.orig
    remote_src: true
    group: named
- name: copy named.conf
  copy:
    src: ./named.conf
    dest: /etc/named.conf
    group: named
- name: create zone file 
  copy:
    src: ./zone-file.conf
    dest: '{{ bind.zone_file_location }}'
    group: named
- name: check the named configuration
  shell: named-checkconf
  register: named_check_ouput
- name: print checking named configuration named_check_ouput
  debug:
    var: named_check_ouput.stdout-lines
- name: restarted named service
  systemd:
    name: named
    state: restarted
    enabled: yes