
- name: authennticate Kerberos credentials
  expect:
    command:  kinit {{ freeipa_user.kerberos_username }}
    responses: "{{ freeipa_user.kerberos_auth_question }}"
    echo: yes

- name: add the user at freeipa
  expect:
    command:  ipa user-add --password  {{ item.user_id }}
    responses:
      'First name:': "{{ item.first_name }}"
      'Last name:': "{{ item.last_name }}"
      'Password:': "{{ item.password }}"
      'Enter Password again to verify:': "{{ item.password }}"
    echo: yes
  with_items: '{{ freeipa_user.user_list }}'
  ignore_errors: yes

- name: add user to the group
  # debug:
  #   msg: ipa group-add-member {{ item.1 }} --users={{ item.0.user_id }}
  command: ipa group-add-member {{ item.1 }} --users={{ item.0.user_id }}
  with_subelements: 
  - "{{ freeipa_user.user_list }}"
  - groups
  ignore_errors: yes