- name: install rsyslog using dnf
  dnf:
    name: rsyslog
    state: present
- name: backup rsyslog configuration
  copy:
    src: /etc/rsyslog.conf
    dest: /etc/rsyslog.conf.{{ansible_date_time.date}}.backup
    remote_src: true
- name: comment out udp module
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^\#module\(load\=\"imudp\"\)'
    line: 'module(load="imudp")'
- name: comment out udp input type and port
  replace:
    path: /etc/rsyslog.conf
    regexp: '^\#input\(type\=\"imudp\" port\=\"514\"\)'
    replace: 'input(type="imudp" port="514")'
- name: comment out tcp module
  replace:
    path: /etc/rsyslog.conf
    regexp: '^\#module\(load\=\"imtcp\"\)'
    replace: 'module(load="imtcp")'
- name: comment out tcp input type and port
  replace:
    path: /etc/rsyslog.conf
    regexp: '^\#input\(type\=\"imtcp\" port\=\"514\"\)'
    replace: 'input(type="imtcp" port="514")'
- name: check template format exist
  command: grep -c "$template" /etc/rsyslog.conf
  register: template_exit
  ignore_errors: yes
- name: add the rsyslog template format
  lineinfile:
    path: /etc/rsyslog.conf
    line: "{{ rsyslog_server.template_format }}"
    insertafter: "EOF"
  when: template_exit.stdout == "0"
- name: create directory for remote log
  file:
    path: "{{ rsyslog_server.remote_log_dir }}"
    state: directory
- name: check the rsyslog cof
  shell: rsyslogd -N1 -f /etc/rsyslog.conf
- name: restart rsyslog service
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes

